server:
  port: 8182
spring:
  application:
    name: activiti
  profiles:
    active: ybd
  # spring-cloud-stream + kafka
  cloud:
    stream:
      instance-count: 1
      instance-index: 0
      kafka:
        binder:
          brokers: 192.168.159.131:9092
          zk-nodes: 192.168.159.131:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        input:
          destination: activiti-topic-test
          group: test-al1
          consumer:
            concurrency: 1
            partitioned: false

