server:
  port: 8182
spring:
  application:
    name: activiti
  profiles:
    active: ybd
  # spring-cloud-stream + kafka
  cloud:
    stream:
      instance-count: 1
      instance-index: 0
      kafka:
        binder:
          brokers: 192.168.159.131:9092
          zk-nodes: 192.168.159.131:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: true
      bindings:
        input:
          destination: activiti-topic-test
          group: test-al1
          consumer:
            concurrency: 1
            partitioned: false


## 顺骋-dev
# rm-bp1oydriw2vi7fc68qo.mysql.rds.aliyuncs.com
# user_ercsc
# Lunz2017

## 浩凯-dev
# rm-bp1oydriw2vi7fc68qo.mysql.rds.aliyuncs.com
# user_erchk
# Lunz2017

# 【996github】https://github.com/996icu/996.ICU